/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nuco_nvmjit_ByteArrayExt */

#ifndef _Included_com_nuco_nvmjit_ByteArrayExt
#define _Included_com_nuco_nvmjit_ByteArrayExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nuco_nvmjit_ByteArrayExt
 * Method:    copyToJNI
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_nuco_nvmjit_ByteArrayExt_copyToJNI
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_nuco_nvmjit_ByteArrayExt
 * Method:    copyFromJNI
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nuco_nvmjit_ByteArrayExt_copyFromJNI
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
